/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Zonewatch REST API route definitions.
 * All routes perform server-side input sanitisation before passing data
 * to the Gemini AI service. Each route has a robust fallback so the
 * platform remains operational even when AI is unavailable.
 */

import { Router, Request, Response } from 'express';
import {
  runWithModelRetry,
  recommendSchema,
  broadcastSchema,
  translateSchema,
  parseFileSchema,
  navigationSchema,
} from '../services/gemini';
import {
  getRecommendFallback,
  getRecommendUltimateFallback,
  getBroadcastScriptFallback,
  getTranslateFallback,
  getParseFileFallback,
} from '../services/fallbacks';
import type {
  Gate,
  ParsedGate,
  RecommendRequestBody,
  BroadcastScriptRequestBody,
  TranslateRequestBody,
  ParseMockFileRequestBody,
  NavigationRequestBody,
} from '../types';
import { sanitise } from '../types';

const router = Router();

// ─── 1. Gate Surge Recommendation ────────────────────────────────────────────

/**
 * POST /api/recommend
 * Analyses a crowd surge at a specific gate and returns tactical guidance,
 * risk assessment, and multilingual megaphone scripts generated by Gemini.
 */
router.post('/recommend', async (req: Request<object, object, RecommendRequestBody>, res: Response) => {
  const { gate, gates, history } = req.body;

  if (!gate?.id || !gate?.name || typeof gate?.density !== 'number' || !Array.isArray(gates)) {
    res.status(400).json({ error: 'Missing or invalid gate context parameters.' });
    return;
  }

  const otherGatesInfo = gates
    .filter((g: Gate) => g.id !== gate.id)
    .map((g: Gate) => `${g.name}: ${g.density}%`)
    .join(', ');

  const historyText =
    Array.isArray(history) && history.length > 1
      ? `Density history over the last few tracking intervals: ${history.join('%, ')}%`
      : `Current trend: ${gate.trend}`;

  const prompt = `You are Zonewatch AI Copilot, a specialist real-time reasoning agent for stadium operations volunteers at the FIFA World Cup 2026.
Your role is to analyze a localized gate crowd surge and return a logical, tactical, easy-to-read recommendation.

CONGESTION ALERT METRICS:
- Target Gate: ${gate.name}
- Current Density: ${gate.density}% (Note: anything above 80% is critical)
- Historical Trend: ${historyText}
- Alternative Sector Gates: ${otherGatesInfo}

TASK:
Produce a tactical alert intervention plan in strict JSON. Keep sentences direct, plain, spoken-style, and impactful.
1. "whatsHappening": A 1-sentence description of the exact situation at the gate.
2. "risk": A 1-sentence risk projection stating what happens if nothing is done, with a rough time estimate.
3. "action": A direct, actionable crowd control action, specifying clear gates for redirection.
4. "scriptEnglish": A short, friendly, spoken-style megaphone announcement in English for stressed tourists.
5. "scriptSpanish": The same announcement translated naturally and warmly into Spanish.
6. "scriptFrench": The same announcement translated naturally and warmly into French.

Respond ONLY with a JSON object containing these exact 6 fields.`;

  try {
    const responseText = await runWithModelRetry(prompt, recommendSchema, 0.2);
    const parsed: Record<string, string> = JSON.parse(responseText);
    res.json(parsed);
  } catch {
    try {
      res.json(getRecommendFallback(gate, gates));
    } catch {
      res.json(getRecommendUltimateFallback(gate, gates));
    }
  }
});

// ─── 2. Megaphone Broadcast Script ───────────────────────────────────────────

/**
 * POST /api/broadcast-script
 * Converts a crowd-control recommendation into empathetic multilingual
 * megaphone announcements for tourists and fans.
 */
router.post('/broadcast-script', async (req: Request<object, object, BroadcastScriptRequestBody>, res: Response) => {
  const raw = req.body;

  const whatsHappening = sanitise(raw.whatsHappening);
  const action = sanitise(raw.action);
  const gateName = sanitise(raw.gateName, 100);

  if (!whatsHappening || !action) {
    res.status(400).json({ error: 'Missing or empty required recommendation parameters after sanitisation.' });
    return;
  }

  const prompt = `You are Zonewatch AI Copilot, a specialist stadium operations reasoning agent for the FIFA World Cup 2026.
Your task is to convert a high-stress operational crowd control recommendation into an empathetic, ultra-clear, spoken megaphone announcement script.

OPERATIONAL BACKGROUND:
- Target Gate: ${gateName || 'the congested gate'}
- What is Happening: ${whatsHappening}
- Proposed Action Plan: ${action}

SCRIPT REQUIREMENTS:
- Audience: tourists and fans who are highly stressed, fatigued, may not speak English well, and are waiting in congested crowd lines.
- Tone: warm, calm, spoken, and friendly (NOT formal PA-system, NOT corporate).
- Instructions: incredibly direct, simple, action-oriented with clear directions.
- Languages: English, Spanish (warm Mexican Spanish), French (warm Canadian/Parisian French).

Respond ONLY with a JSON object containing:
- "scriptEnglish": short, supportive, easy-to-understand spoken announcement.
- "scriptSpanish": Spanish translation with the same warm, spoken feel.
- "scriptFrench": French translation with the same warm, spoken feel.`;

  try {
    const responseText = await runWithModelRetry(prompt, broadcastSchema, 0.3);
    const parsed: Record<string, string> = JSON.parse(responseText);
    res.json(parsed);
  } catch {
    res.json(getBroadcastScriptFallback(gateName));
  }
});

// ─── 3. Multilingual Supporter Translation & Triage ──────────────────────────

/**
 * POST /api/translate
 * Translates a supporter's phrase, classifies urgency level, and returns a
 * compassionate suggested response in the supporter's original language.
 */
router.post('/translate', async (req: Request<object, object, TranslateRequestBody>, res: Response) => {
  const raw = req.body;
  const phrase = sanitise(raw.phrase);

  if (!phrase) {
    res.status(400).json({ error: 'Missing required supporter voice phrase.' });
    return;
  }

  let toneContext = '';
  if (raw.vocalTone) {
    const { detectedTone, pitch, speed, volume } = raw.vocalTone;
    const cleanTone   = sanitise(detectedTone, 100) || 'N/A';
    const cleanPitch  = sanitise(pitch, 100)  || 'Normal';
    const cleanSpeed  = sanitise(speed, 100)  || 'Normal';
    const cleanVolume = sanitise(volume, 100) || 'Normal';

    toneContext = `
Additionally, a real-time vocal acoustic detector analyzed the supporter's audio and found:
- Detected Vocal Tone: ${cleanTone}
- Estimated Pitch Level: ${cleanPitch}
- Speech Speed: ${cleanSpeed}
- Average Loudness: ${cleanVolume}

Please factor this acoustic tone and emotional profile into your triage reasoning.`;
  }

  const prompt = `You are Zonewatch AI Translation Copilot, a real-time language translation and emergency triage agent for stadium volunteers at the FIFA World Cup 2026.
You are given a phrase spoken by a supporter: "${phrase}"${toneContext}

Your task is to:
1. Identify the original language of the phrase.
2. Translate the phrase accurately and concisely into English.
3. Classify the request's urgency into exactly one of: "Casual", "Urgent", "Medical", or "Accessibility".
4. Provide a 1-sentence logical operational reasoning for this classification.
5. Generate a short, compassionate, helpful response to the supporter in their ORIGINAL language.
6. Provide an English translation of the generated response so the volunteer understands it.
7. Classify the supporter's emotional vocal tone based on semantic cues.

Respond ONLY with a JSON object containing these exact fields:
- "originalLanguage", "translatedText", "urgencyTag", "classificationReason",
  "suggestedResponse", "suggestedResponseEnglish", "detectedTone"`;

  try {
    const responseText = await runWithModelRetry(prompt, translateSchema, 0.3);
    if (!responseText) throw new Error('Empty response from Gemini.');
    const parsed: Record<string, string> = JSON.parse(responseText);
    res.json(parsed);
  } catch {
    res.json({ ...getTranslateFallback(phrase), isLocalFallback: true });
  }
});

// ─── 4. Mock Telemetry File Parser ────────────────────────────────────────────

/**
 * POST /api/parse-mock-file
 * Parses an uploaded CSV or PDF telemetry file, first attempting a fast
 * local CSV parser, then falling back to Gemini multimodal parsing.
 */
router.post('/parse-mock-file', async (req: Request<object, object, ParseMockFileRequestBody>, res: Response) => {
  const { base64Data, fileType, fileName } = req.body;

  if (!base64Data) {
    res.status(400).json({ error: 'No file content provided.' });
    return;
  }

  try {
    console.log(`Received mock file upload: ${fileName || 'unnamed'} (Type: ${fileType})`);
    let parsedGates: ParsedGate[] = [];
    let summaryOfChanges = '';
    let usedLocalFallback = false;

    /** Parses a CSV text string into an array of ParsedGate objects. */
    const parseCsvLocally = (csvText: string): ParsedGate[] => {
      const HEADER_KEYWORDS = new Set(['gate', 'name', 'gate name', 'gatename', 'gate_name']);
      const lines = csvText.split(/\r?\n/);
      const result: ParsedGate[] = [];

      for (const line of lines) {
        if (!line.trim()) continue;
        const parts = line.split(/[,\t;]/).map((p) => p.trim());
        if (parts.length < 2) continue;

        const rawName = parts[0];
        if (HEADER_KEYWORDS.has(rawName.toLowerCase())) continue;

        let density = 50;
        let foundNumber = false;
        for (let i = 1; i < parts.length; i++) {
          const num = parseInt(parts[i].replace(/%/g, ''), 10);
          if (!isNaN(num) && num >= 0 && num <= 100) {
            density = num;
            foundNumber = true;
            break;
          }
        }

        if (!foundNumber && !rawName.toLowerCase().startsWith('gate')) continue;

        const name = rawName.charAt(0).toUpperCase() + rawName.slice(1);
        const id = name.toLowerCase().replace(/[^a-z0-9]/g, '-');

        let trend: 'up' | 'down' | 'stable' = 'stable';
        for (const part of parts) {
          const lp = part.toLowerCase();
          if (['up', 'rising', 'increase', 'upward'].includes(lp)) { trend = 'up'; break; }
          if (['down', 'falling', 'decrease', 'downward'].includes(lp)) { trend = 'down'; break; }
        }

        // Generate a realistic 5-point history window matching the trend.
        const history: number[] = [];
        let current = density;
        for (let step = 0; step < 5; step++) {
          history.unshift(Math.max(5, Math.min(100, current)));
          if (trend === 'up') current -= Math.floor(Math.random() * 4) + 2;
          else if (trend === 'down') current += Math.floor(Math.random() * 4) + 2;
          else current += Math.floor(Math.random() * 3) - 1;
        }

        result.push({ id, name, density, trend, history });
      }
      return result;
    };

    // Attempt fast local CSV parsing first to avoid Gemini quota usage.
    if (fileType === 'csv') {
      try {
        const rawText = Buffer.from(base64Data, 'base64').toString('utf-8');
        const localResult = parseCsvLocally(rawText);
        if (localResult.length > 0) {
          parsedGates = localResult;
          summaryOfChanges = `Successfully parsed ${parsedGates.length} gates locally from uploaded CSV file.`;
          console.log('Local CSV parser successfully processed the file.');
        }
      } catch (localErr) {
        console.warn('Local CSV parser failed, proceeding to Gemini:', localErr);
      }
    }

    // Fall back to Gemini multimodal parsing for PDFs or failed CSV parses.
    if (parsedGates.length === 0) {
      const mimeType = fileType === 'pdf' ? 'application/pdf' : 'text/csv';
      const geminiPrompt = `You are a specialized telemetry data parser for stadium gate spectator counts.
Analyze the attached file content representing gate status/density values.
Extract: gate name, density % (0-100), trend (up/down/stable), and a 5-point history array.
Generate a unique id per gate (e.g. 'gate-b'). Provide a summaryOfChanges sentence.`;

      try {
        const promptContents = [
          { inlineData: { mimeType, data: base64Data } },
          { text: geminiPrompt },
        ];
        const responseText = await runWithModelRetry(promptContents, parseFileSchema, 0.1);
        if (responseText) {
          const data = JSON.parse(responseText) as { gates?: ParsedGate[]; summaryOfChanges?: string };
          if (data.gates && data.gates.length > 0) {
            parsedGates = data.gates;
            summaryOfChanges = data.summaryOfChanges
              ?? `Gemini successfully parsed ${data.gates.length} gates from your uploaded ${fileType.toUpperCase()} file.`;
          }
        }
      } catch (geminiErr) {
        console.error('Gemini file parser failed:', geminiErr instanceof Error ? geminiErr.message : geminiErr);
        usedLocalFallback = true;
        parsedGates = getParseFileFallback();
        summaryOfChanges = 'Using local backup telemetry engine to simulate a localized crowd surge scenario.';
      }
    }

    const finalizedGates: ParsedGate[] = parsedGates.map((gate) => {
      const density = Math.max(0, Math.min(100, typeof gate.density === 'number' ? gate.density : parseInt(String(gate.density)) || 50));
      const rawTrend = (gate.trend ?? 'stable').toLowerCase();
      const trend = (['up', 'down', 'stable'].includes(rawTrend) ? rawTrend : 'stable') as 'up' | 'down' | 'stable';
      const history = Array.isArray(gate.history) && gate.history.length === 5
        ? gate.history
        : [density, density, density, density, density];

      return {
        id: gate.id || `gate-${Math.random().toString(36).substring(2, 7)}`,
        name: gate.name || `Gate ${gate.id?.toUpperCase() ?? 'Custom'}`,
        density,
        trend,
        history,
      };
    });

    res.json({
      success: finalizedGates.length > 0,
      gates: finalizedGates,
      summaryOfChanges: summaryOfChanges || `Parsed ${finalizedGates.length} gates.`,
      usedLocalFallback,
    });

  } catch (err) {
    console.error('Parse Mock File Error:', err);
    res.status(500).json({ error: err instanceof Error ? err.message : 'An error occurred while parsing the file.' });
  }
});

// ─── 5. GenAI Stadium Navigation ─────────────────────────────────────────────

/**
 * POST /api/navigation
 * Provides AI-powered multilingual stadium wayfinding assistance.
 * Covers accessibility, crowd-flow optimisation, and real-time decision
 * support — core pillars of the FIFA World Cup 2026 problem statement.
 */
router.post('/navigation', async (req: Request<object, object, NavigationRequestBody>, res: Response) => {
  const query = sanitise(req.body.query);
  const assignedGate = sanitise(req.body.assignedGate, 100);
  const language = sanitise(req.body.language || 'English', 50);

  if (!query) {
    res.status(400).json({ error: 'Navigation query is required.' });
    return;
  }

  const prompt = `You are Zonewatch Navigation Copilot, a multilingual AI wayfinding agent for the FIFA World Cup 2026 stadium.
A fan or volunteer has asked the following navigation question: "${query}"
Volunteer's assigned gate sector: ${assignedGate || 'Unknown'}
Fan's preferred language: ${language}

Your task:
1. Provide clear, step-by-step walking directions relevant to a stadium environment.
2. Reference recognisable landmarks (gates, concession stands, first aid, accessibility ramps).
3. Estimate realistic walking time in minutes.
4. Note any accessibility considerations (elevator location, wheelchair ramps, quiet corridors).
5. Provide the full route guidance in the fan's preferred language as "inOriginalLanguage".

Respond ONLY with a JSON object:
- "route": Step-by-step English walking directions.
- "landmarks": Array of landmark names along the route.
- "estimatedWalkMinutes": Integer walk time in minutes.
- "accessibilityNote": Accessibility tip (or empty string if none).
- "inOriginalLanguage": Full route guidance in the fan's preferred language (${language}).`;

  const fallbackNavigation = {
    route: `From your current position near ${assignedGate || 'your gate'}, follow the main concourse signs. Stadium staff are stationed at every junction to assist you.`,
    landmarks: ['Main Concourse', 'Gate Signage', 'Information Desk', 'First Aid Station'],
    estimatedWalkMinutes: 5,
    accessibilityNote: 'Wheelchair ramps and elevators are available near every gate entrance. Ask any volunteer for assistance.',
    inOriginalLanguage: `Please follow stadium signage or ask any volunteer in the red jacket for directions. We are here to help!`,
    isLocalFallback: true,
  };

  try {
    const responseText = await runWithModelRetry(prompt, navigationSchema, 0.3);
    if (!responseText) throw new Error('Empty response from Gemini.');
    const parsed = JSON.parse(responseText) as Record<string, unknown>;
    res.json(parsed);
  } catch {
    res.json(fallbackNavigation);
  }
});

export default router;
